---
exclude:
  - "**/bin/**/*"
  - "**/db/**/*"
  - "**/vendor/**/*"
  - "**/tmp/**/*"
  - "**/node_modules/**/*"
linters:
  AllowedScriptType:
    enabled: true
    allowed_types:
      - "application/json"
      - "text/javascript"
      - "text/html"
      - "module"
    allow_blank: false
    disallow_inline_scripts: false
  ErbSafety:
    enabled: false
  FinalNewline:
    enabled: true
  HardCodedString:
    enabled: false
  ParserErrors:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/CommentIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Layout/LineLength:
        Enabled: false
  SelfClosingTag:
    enabled: false
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  SpaceIndentation:
    enabled: true
  TrailingWhitespace:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
